---
- hosts: kubernetes
  become: true
  tasks:
    - name: Check if cmdline exists
      stat:
        path: /boot/cmdline
      register: cmdline_stat 

    - name: Create /boot/cmdline file
      copy:
        content: "cgroup_enable=memory"
        dest: /boot/cmdline
      when: not cmdline_stat.stat.exists

    - name: Append line to /boot/cmdline
      lineinfile:
        path: /boot/cmdline
        line: "cgroup_enable=memory"
        insertafter: EOF
        state: present
      when: cmdline_stat.stat.exists

    - name: Reboot server
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0

    - name: Disable swap
      command: swapoff -a

    - name: Ensure br_netfilter is enabled.
      modprobe:
        name: br_netfilter
        state: present

    - name: Let iptables see bridged traffic.
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: Apply new settings
      command: sudo sysctl --system

- hosts: kubemaster
  become: true
  tasks:
    - name: allow 6443 port
      ufw:
        rule: allow
        port: 6443
        proto: tcp

- hosts: kubernetes
  become: true
  roles:
    - geerlingguy.containerd

- hosts: kubernetes
  become: true
  vars:
    kubernetes_allow_pods_on_control_plane: true
    kubernetes_config_init_configuration:
      localAPIEndpoint:
        advertiseAddress: "0.0.0.0"
      nodeRegistration:
        criSocket: "unix:///run/containerd/containerd.sock"
      skipPhases:
        - addon/kube-proxy
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

- hosts: kubemaster[0]
  become: true
  tasks:
    - name: wait 40s
      pause:
        seconds: 40
    - name: setup kube-proxy
      command: kubeadm init phase addon kube-proxy --control-plane-endpoint={{ hostvars[groups['kubemaster'][0]]['ansible_host'] }}:6443 --pod-network-cidr="10.0.0.0/24"

- hosts: kubemaster[0]
  become: true
  tasks:
    - name: fetch kubeconfig
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes