name: Build OS Image

on:
  push:
    branches:
      - main
    paths:
      - 'packer/**'
      - '.github/workflows/build-os-image.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 1.8.7
      - name: Setup public ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          known_hosts: unnecessary
          name: remote_machines.pub
      - name: Packer Init
        working-directory: ./configs/packer/${{ matrix.os }}
        run: packer init .
      - name: Packer Validate
        working-directory: ./configs/packer/${{ matrix.os }}
        run: packer validate -var hcloud_token=${{ secrets.HCLOUD_TOKEN }} .
      - name: Packer Build
        working-directory: ./configs/packer/${{ matrix.os }}
        run: packer build -var hcloud_token=${{ secrets.HCLOUD_TOKEN }} .
    