name: Image Cleaner Build

on:
  push:
    branches:
      - main
    paths:
      - 'development/image-cleaner/**'
      - '.github/workflows/image-cleaner.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - run: go test ./...
      - run: ko build -B --platform=linux/amd64 ./development/image-cleaner