name: Checkov

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: none

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: './'
          framework: 'dockerfile'
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: './'
          framework: 'github_configuration'
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: './'
          framework: 'terraform'
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: './'
          framework: 'ansible'