name: Clean Up Old Hetzner Images (Snapshots)

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: [db-ubuntu-*, k3s-ubuntu-*, base-ubuntu-*]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Image Cleaner
        run: docker run ghcr.io/edplanes/test-infra/image-cleaner:main list -t ${{ secrets.HCLOUD_TOKEN }} -o 7d -f ${{ matrix.images }} -u
            
        