name: Spell Checker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - run: ko build -B --platform=linux/amd64 ./development/spell-checker