name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - configs/terraform/**/*
      - configs/ansible/**/*
      - .github/workflows/terraform-apply.yml
      - requirements.yml

permissions:
  contents: read

env:
  CONFIG_DIRECTORY: "./configs/terraform"

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Apply
    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Init
        id: init
        working-directory: ${{ env.CONFIG_DIRECTORY }}
        run: terraform init -input=false -no-color
 
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
      
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    name: Ansible Playbook
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

      - name: Install SSH private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary

      - name: Install SSH public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: unnecessary

      - name: Install ansible dependencies
        working-directory: ./configs/ansible
        run: |
          if [ -f collections/requirements.yml ]; then ansible-galaxy install -r collections/requirements.yml; fi

      - name: Run ansible playbook
        working-directory: ./configs/ansible
        run: |
          ansible-playbook playbook.yml
      