name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: cat $GITHUB_EVENT_PATH
